#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
language: c
sudo: false

env:
    global:
    - BYOND_MAJOR="508"
    - BYOND_MINOR="1293"
    matrix:
    - DM_MAPFILE="tgstation2"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"

before_install:
  - apt-get update -qq
  - apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq
  - apt-get install python -qq
  - apt-get install python-pip -qq
  - pip install PyYaml -q
  - pip install beautifulsoup4 -q

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - make install
  - cd ..

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
