[package]
name = "ss13script"
version = "0.1.0"
authors = ["McDonald072"]

[dependencies]
libc = "0.2"
lazy_static = "1.1.0"
encoding = "0.2"
log = "0.4"
simplelog = "^0.5.0"

[lib]
crate-type = ["lib", "cdylib"]