name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v3.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.
          stale-pr-message: "This pull request has been inactive for 5 days, it will be closed in 3 days if there still is no activity."
          days-before-stale: 5
          days-before-close: 3
          stale-pr-label: "Stale"
          only-labels: "Awaiting - Action - Author"
          operations-per-run: 30
          remove-stale-when-updated: true
